name: Unity Build
on:
  push:
    branches: master
  pull_request: 
    branches: master
  workflow_dispatch: {}
  
jobs:
  unity-build:
    name: Run the unity build steps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Cache
        uses: actions/cache@main
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Run the Android build
        uses: game-ci/unity-builder@main
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          unityVersion: 2022.3.58f1
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: Build
          path: build